<a href="https://colab.research.google.com/github/yunju-m/MachineLearning/blob/main/MachineLearning__02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기계학습 2주차 실습

## 시작하기 전에..

※ 상단 메뉴에서 '**파일 - 드라이브에 사본 저장**' 진행 후 시작하세요.

---

1. 구글 Colab의 기초 사용법을 숙지해보자. 예시의 결과가 출력되도록 아래 스텝을 따라가시오.

- 결괏값을 반환해주는 get_result 함수를 구현하기 위해 코드 위에 새로운 코드셀을 추가해보자.\
옳지 않은 곳에 셀을 생성했다면 셀 우측 상단의 화살표 버튼을 통해 이동시킬 수 있다.

- 생성한 셀에 "Hello world" 문자열을 출력하는 함수 get_result를 정의해보자.

- 셀들은 독자적으로 실행 될 수 있다. 셀에 마우스를 올리면 좌측에 실행버튼이 생긴다. 이를 통해 두 셀들을 실행하여 결과를 확인해보자.\
또는 셀 에디터 내에서 Ctrl+Enter로 실행할 수 있다.

In [ ]:
def get_result():
  return "Hello world"

In [ ]:
result = get_result()

print("결과:", result)

결과: Hello world


- 코랩은 작성한 순서가 아닌 셀이 실행된 순서대로 정보가 쌓인다.\
이를 이해하기 위해 바로 아래의 코드를 실행해보고 결과를 다시 출력해보자.

In [ ]:
def get_result():
  return "New Result"

In [ ]:
result = get_result()

print("결과:", result)

결과: New Result


- 이런 이유로 실행 순서로 인해 예상하지 않은 결과가 나오는 경우가 자주 생긴다.\
그럴 경우에는 상단 메뉴 중 **'런타임 - 다시 시작 및 모두 실행'**으로 쌓인 정보를 모두 지우고 차례대로 다시 실행할 수 있다.

---

2. 계산기(calculator) class를 만들어보자.

*  조건 1. 계산기는 두 실수를 입력으로 받을 수 있다.
*  조건 2. 계산기 기능은 add(+), sub(-), multiply(*), divide(/) 이렇게 4개 이다.
*  조건 3. while 문을 돌면서, 두 개의 숫자를 입력으로 받고 사칙 연산 중 하나를 선택하면, 해당 연산을 수행하고, 특정 값이 나오면 while문을 탈출한다.

In [ ]:
## 두 실수에 대한 4칙 연산이 정의된 클래스
class Calculator():
  def set_a(obj, x):
    obj.a = x
  def set_b(obj, x):
    obj.b = x
  def add(obj):
    return obj.a + obj.b
  def sub(obj):
    return obj.a - obj.b
  def mul(obj):
    return obj.a * obj.b
  def div(obj):
    if obj.b == 0:
      return "ZeroDivisionError"
    return obj.a / obj.b

# ========================= #

obj=Calculator() ## Calculator라는 class를 obj이라는 이름의 객체로 생성

while True:
    a=float(input("Enter first number: "))
    obj.set_a(a)

    b=float(input("Enter second number: "))
    obj.set_b(b)
    
    print("0. Exit")
    print("1. Add")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    choice=int(input("Enter choice: "))
    
    if choice==1:
        print("Result: ",obj.add())
    elif choice==2:
        print("Result: ",obj.sub())
    elif choice==3:
        print("Result: ",obj.mul())
    elif choice==4:
        print("Result: ",obj.div())
    elif choice==0:
        print("Exiting!")
        break
    else:
        print("Invalid choice!!")
    print("")

Enter first number: 5
Enter second number: 4
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 1
Result:  9.0

Enter first number: 5
Enter second number: 4
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 2
Result:  1.0

Enter first number: 5
Enter second number: 4
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 3
Result:  20.0

Enter first number: 5
Enter second number: 4
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 4
Result:  1.25

Enter first number: 5
Enter second number: 0
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 4
Result:  ZeroDivisionError

Enter first number: 0
Enter second number: 0
0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division
Enter choice: 0
Exiting!


---

3. 모듈의 사용법을 익혀보자.
- math 모듈을 import 하시오.
- random 모듈 내부에 정의돼있는 randint 함수를 import 하시오.
- numpy 라는 모듈을 import 하되, np라는 약칭으로 쓸 수 있도록 import 하시오.

In [ ]:
### 1.
import math
print("4! =", math.factorial(4))
print("log₂64 =", math.log(64, 2))

### 2.
from random import randint
print("1~5 랜덤 숫자:", randint(1, 5))

### 3.
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("x의 transpose:\n", x.T)

4! = 24
log₂64 = 6.0
1~5 랜덤 숫자: 1
x의 transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


---

## 마치며..

※ 완료 시 우측 상단 프로필 옆 '**공유 - 액세스를 *링크가 있는 모든 사용자*로 전환**' 후 복사한 링크를 이루리 과제 란에 업로드 하세요.

<img src="https://drive.google.com/uc?id=1Zj1FKIz0sanqUfkfr3scp5M-dDgMFxYQ" height=300>

</br>

※ 추가로 상단 메뉴 '**파일 - 다운로드 - .ipynb**' 로 다운로드 후 첨부 파일로 업로드 하세요.

※ 즉, 과제의 텍스트란에는 링크를, 파일 첨부란에는 .ipynb 파일을 제출하십시오.